filters:
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "â­ goal: addition"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]
  - label: "ğŸ“„ aspect: docs"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
  - label: "ğŸ›  goal: fix"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]

  
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /build/i
    events: [pull_request]
    targets: [title]
  - label: "ğŸ›  goal: fix"
    regexs:
      - /build/i
    events: [pull_request]
    targets: [title]
