filters:
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "ğŸ›  Feature"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]
  - label: "ğŸ“„ aspect: docs"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  
  - label: "ğŸ‘·ğŸ»â€â™‚ï¸ status: awaiting triage"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
  - label: "ğŸ Bug"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
