filters:
  - label: "status: todo â³"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  - label: "ğŸ’¡ feature"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  - label: "status: todo â³"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  - label: "ğŸ“š docs"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  - label: "status: todo â³"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]

  - label: "ğŸ bug"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]