name: E2E Tests on Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # use docker container to run tests
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Cypress Tests - Chrome"
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          install: true # Install project dependencies
          build: vite build # Create production build for testing
          start: npm run dev # Start development server on docker container
          wait-on: "http://localhost:5173/" # wait on the project to start before running tests
          wait-on-timeout: 120 # amount of time to wait on server to start
          browser: chrome # Specify browser to run tests on
          spec: cypress/e2e/* # Specify the test files you'd like to run
        env:
          # temporary fix for eslint warnings being treated as errors.
          # This works for "react": "^17.0.2" and "react-scripts": "^5.0.1". Upgrading any of these packages
          # means that you will have to change this to CI=false
          CI: ""
